PREFIX vers: <https://github.com/GreenfishK/DataCitation/versioning/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

select *
where {
    {select ?x ?y ?z
        where { 
            service <https://dbpedia.org/sparql> {
                SELECT *
                WHERE {
                    VALUES ?x { <{:rdf_store_url}> }
                    { <{:rdf_store_url}> ?y ?z }
                }
            }
        }
    }
    filter not exists
    {select ?x ?y ?z {
            << <<?x ?y ?z>> vers:valid_from ?valid_from_1 >> vers:valid_until ?valid_until_1.
			filter(?valid_from_1 <= ?tsBGP_0 && ?tsBGP_0 < ?valid_until_1)

			bind("2024-02-27T08:24:51.863+00:00"^^xsd:dateTime as ?tsBGP_0)
        }
    }
}