version: "3"

services:
  starversserver:
    image: starversserver # should be changed to ghcr.io/martinmitteregger/starversserver:main
    restart: always
    ports:
      - 80:80
    env_file: "../prod.env"
    volumes:
      - /mnt/data/starversserver/evaluation:/code/evaluation
      - /mnt/data/starversserver/logs:/code/logs
      - /mnt/data/starversserver/graphdb-data/graphdb-import:/graphdb-import
    depends_on:
      db:
        condition: service_started
      rdfstore:
        condition: service_started
    entrypoint: ["fastapi", "run", "app/main.py", "--port", "80"]
  
  gui:
    image: starversserver # should be changed to ghcr.io/martinmitteregger/starversserver:main
    ports:
      - 5000:5000
    volumes:
      - ../app/gui:/code/app/gui
      - /mnt/data/starversserver/evaluation:/code/evaluation
      - /mnt/data/starversserver/logs:/code/logs
    depends_on:
      db:
        condition: service_started
      rdfstore:
        condition: service_started
    env_file: "../prod.env"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint: ["python", "app/run_gui.py"]

  retroVersioning:
    image: starversserver
    env_file: "../prod.env"
    ports: 
      - 80:80
    volumes:
      - /mnt/data/starversserver/evaluation:/code/evaluation
      - /mnt/data/starversserver/logs:/code/logs
      - /mnt/data/starversserver/graphdb-data/graphdb-import:/graphdb-import
    entrypoint: ["python", "app/utils/RetroVersioning.py", "schema_org_ontology", "SPARQL", "rdf"]


  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: starvers_db
    ports:
      - 5432:5432
    volumes:
      - /mnt/data/starversserver/postgresql:/var/lib/postgresql


  rdfstore:
    image: ontotext/graphdb:10.5.0
    restart: always
    environment: 
      GDB_JAVA_OPTS: >-
        -Xmx32g -Xms32g
        -Dgraphdb.home=/opt/graphdb/home
        -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
        -Dgraphdb.workbench.cors.enable=true
        -Denable-context-index=true
        -Dentity-pool-implementation=transactional
        -Dhealth.max.query.time.seconds=60
        -Dgraphdb.append.request.id.headers=true
        -Dreuse.vars.in.subselects=true
        -Dgraphdb.health.minimal.free.storage.enabled=false
        -Dgraphdb.health.minimal.free.storage.asyncCheck=false
    ports: 
      - 7200:7200
      - 7300:7300
    volumes:
      - /mnt/data/starversserver/graphdb-data:/opt/graphdb/home
    extra_hosts:
      - "host.docker.internal:host-gateway"
  

