version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: starvers_db
    ports:
      - 5432:5432


  rdfstore:
    image: ontotext/graphdb:10.5.0
    restart: always
    environment: 
      GDB_JAVA_OPTS: >-
        -Xmx8g -Xms8g
        -Dgraphdb.home=/opt/graphdb/home
        -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
        -Dgraphdb.workbench.cors.enable=true
        -Denable-context-index=true
        -Dentity-pool-implementation=transactional
        -Dhealth.max.query.time.seconds=60
        -Dgraphdb.append.request.id.headers=true
        -Dreuse.vars.in.subselects=true
        -Dgraphdb.health.minimal.free.storage.enabled=false
        -Dgraphdb.health.minimal.free.storage.asyncCheck=false
    ports: 
      - 7200:7200
      - 7300:7300
    volumes:
      - ./graphdb-data:/opt/graphdb/home
    extra_hosts:
      - "host.docker.internal:host-gateway"