PREFIX vers: <https://github.com/GreenfishK/DataCitation/versioning/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT (distinct ?valid_from as ?latest_update_ts)
WHERE {
    << <<?s ?p ?o>> vers:valid_from ?valid_from >> vers:valid_until ?valid_until .
} 
order by desc(?version_ts)
limit 1